// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-keys.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
import { z } from "npm:zod@^3.25.76";
function client() {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_keys_default = defineTool({
  name: "list_keys",
  title: "List proxy keys",
  description: "List proxy keys, optionally filtered by status (Activa, Usada, Expirada, Bloqueada).",
  inputSchema: {
    status: z.enum(["Activa", "Usada", "Expirada", "Bloqueada"]).optional().describe("Filter by status."),
    limit: z.number().int().positive().optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }) => {
    const sb = client();
    let q = sb.from("proxy_keys").select("key,type,status,duration,created_at,used_by,expires_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { keys: data }
    };
  }
});

// src/lib/mcp/tools/generate-keys.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.3";
import { z as z2 } from "npm:zod@^3.25.76";
function client2() {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function generateKey() {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  const seg = () => Array.from({ length: 4 }, () => chars[Math.floor(Math.random() * chars.length)]).join("");
  return `PROXY-${seg()}-${seg()}`;
}
var DURATIONS = {
  "1 minuto": 6e4,
  "1 d\xEDa": 864e5,
  "7 d\xEDas": 7 * 864e5,
  "30 d\xEDas": 30 * 864e5
};
var generate_keys_default = defineTool2({
  name: "generate_keys",
  title: "Generate proxy keys",
  description: "Generate one or more proxy keys with a given type and duration. Uses same schema as the admin panel.",
  inputSchema: {
    count: z2.number().int().min(1).max(50).describe("Number of keys to generate (1-50)."),
    type: z2.enum(["Normal", "Premium"]).describe("Key type."),
    duration: z2.enum(["1 minuto", "1 d\xEDa", "7 d\xEDas", "30 d\xEDas"]).describe("Key duration.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ count, type, duration }) => {
    const sb = client2();
    const rows = Array.from({ length: count }, () => ({
      key: generateKey(),
      type,
      status: "Activa",
      duration,
      duration_ms: DURATIONS[duration],
      created_at: (/* @__PURE__ */ new Date()).toISOString()
    }));
    const { data, error } = await sb.from("proxy_keys").insert(rows).select("key,type,status,duration");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Generadas ${data?.length ?? 0} keys:
${data?.map((k) => k.key).join("\n")}` }],
      structuredContent: { keys: data }
    };
  }
});

// src/lib/mcp/tools/list-active-users.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.3";
import { z as z3 } from "npm:zod@^3.25.76";
function client3() {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_active_users_default = defineTool3({
  name: "list_active_users",
  title: "List active users",
  description: "List currently active/logged-in users of the proxy.",
  inputSchema: {
    limit: z3.number().int().positive().optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const sb = client3();
    const { data, error } = await sb.from("active_users").select("name,key,type,login_at,expires_at,blocked").order("login_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { users: data }
    };
  }
});

// src/lib/mcp/tools/block-user.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.3";
import { z as z4 } from "npm:zod@^3.25.76";
function client4() {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var block_user_default = defineTool4({
  name: "set_user_blocked",
  title: "Block or unblock user",
  description: "Set the blocked state for an active user identified by their key.",
  inputSchema: {
    key: z4.string().min(1).describe("The proxy key of the user."),
    blocked: z4.boolean().describe("True to block, false to unblock.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ key, blocked }) => {
    const sb = client4();
    const { error } = await sb.from("active_users").update({ blocked }).eq("key", key);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Usuario ${key} ${blocked ? "bloqueado" : "desbloqueado"}.` }] };
  }
});

// src/lib/mcp/tools/stock.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.99.3";
function client5() {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var stock_default = defineTool5({
  name: "get_stock",
  title: "Get key stock",
  description: "Return counts of available (Activa) proxy keys grouped by type and duration.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const sb = client5();
    const { data, error } = await sb.from("proxy_keys").select("type,duration").eq("status", "Activa");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const counts = {};
    for (const r of data ?? []) {
      const k = `${r.type} \u2014 ${r.duration}`;
      counts[k] = (counts[k] ?? 0) + 1;
    }
    const lines = Object.entries(counts).map(([k, v]) => `${k}: ${v}`).join("\n") || "Sin stock disponible.";
    return {
      content: [{ type: "text", text: lines }],
      structuredContent: { total: data?.length ?? 0, breakdown: counts }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "rave-auxiliar-mcp",
  title: "Rave Auxiliar MCP",
  version: "0.1.0",
  instructions: "Herramientas para administrar Rave Auxiliar: listar y generar proxy keys, ver usuarios activos, bloquear/desbloquear y consultar el stock.",
  tools: [list_keys_default, generate_keys_default, list_active_users_default, block_user_default, stock_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
